name: Module 01 - C Input/Output Games - Check

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  check-exercises:
    runs-on: ubuntu-latest
    steps:
      - name: Code recovery
        uses: actions/checkout@v4

      - name: Tools installation
        run: sudo apt-get update && sudo apt-get install -y gcc valgrind

      - name: Change directory
        run: cd 01-c-io-games

      - name: Hello World
        shell: bash
        run: |
          cd 00-hello-world
          chmod +x ./check.sh
          ./check.sh
          cd ..

      - name: Strlen
        shell: bash
        run: |
          cd 01-strlen
          chmod +x ./check.sh
          ./check.sh
          cd ..