name: Module 00 - C Re Introduction - Check

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  check-exercises:
    runs-on: ubuntu-latest
    steps:
      - name: Code recovery
        uses: actions/checkout@v4

      - name: Tools installation
        run: sudo apt-get update && sudo apt-get install -y gcc valgrind

      - name: Change directory
        run: cd 00-c-re-introduction

      - name: Run all exercise checks
        shell: bash
        run: |
          for dir in ./*; do
            if [ -f "$dir/check.sh" ]; then
              echo "Checking $dir"
              cd "$dir"
              chmod +x check.sh
              ./check.sh
              cd ..
            fi
          done